language: ruby
rvm:
  - "2.1.1"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl-ttf2.0-dev libsndfile-dev libxinerama-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
